const constants = {
  expirationTimestampAfter2Days: Date.now() + 2 * 24 * 60 * 60 * 1000,
  externalApiEndpoint: "",
  table: {
    userTabAccess: {
      columns: [
        "fieldvisits",
        "projectRescue",
        "projectGobiShelter",
        "projectRehabilitationHomeClients",
        "projectRehabilitationHomeActivityTracker",
        "projectRehabilitationHomeFoodMenu",
        "projectRehabilitationHomeVisitors",
        "projectECRC",
        "projectAwarenessProgram",
        "projectHumanitarianServices",
        "outPatientServices",
        "profilesClients",
        "profilesVolunteers",
        "profilesInformers",
        "profilesOtherHomes",
        "profilesStaffs",
        "programTimelines",
        "enquiries",
      ],
    },
    fieldVisits: {
      columns: [
        "ot_regno",
        "outreach_date",
        "client_name",
        "age",
        "gender",
        "health_condition",
        "type_of_addiction",
        "cause_of_beginning",
        "income_from_begging",
        "education_qualification",
        "location_address",
        "client_pic",
        "service_providing_details",
        "approval_status",
        "admin_remarks",
      ],
    },
    projectRescue: {
      columns: [
        "regno",
        "client_name",
        "rescue_date",
        "family_details",
        "age",
        "gender",
        "education_qualification",
        "id_proofs",
        "rescue_location",
        "health_condition",
        "attachments",
        "client_pic",
        "social_reintegration",
        "approval_status",
        "admin_remarks",
      ],
    },
    projectGobiShelter: {
      columns: [
        "client_admission_no",
        "admission_date",
        "client_name",
        "age",
        "gender",
        "health_condition",
        "rescue_location",
        "client_native",
        "client_parent_details",
        "id_proofs",
        "attachments",
        "client_pic",
        "date_of_abscond",
        "approval_status",
        "admin_remarks",
      ],
    },
    projectRehabilitationHomeClients: {
      columns: [
        "client_admission_no",
        "admission_date",
        "client_name",
        "age",
        "gender",
        "health_condition",
        "rescue_location",
        "client_native",
        "client_parent_details",
        "id_proofs",
        "attachments",
        "client_pic",
        "date_of_abscond",
        "approval_status",
        "admin_remarks",
      ],
    },
    projectRehabilitationHomeActivityTracker: {
      columns: [
        "regno",
        "admission_date",
        "client_name",
        "age",
        "gender",
        "health_condition",
        "rescue_location",
        "family_details",
        "food_taken",
        "medicine_taken",
        "exercise_status",
        "grooming_status",
        "abscond_date",
        "social_reintegration",
        "attachments",
        "client_pic",
        "approval_status",
        "admin_remarks",
      ],
    },
    projectRehabilitationHomeFoodMenu: {
      columns: [
        "week_day",
        "breakfast",
        "lunch",
        "dinner",
        "color_code",
        "approval_status",
        "admin_remarks",
      ],
    },
    projectRehabilitationHomeVisitors: {
      columns: [
        "visitor_name",
        "date_of_visit",
        "visitor_designation",
        "place_of_visit",
        "staff_attended",
        "pupose_of_visit",
        "contact_no",
        "approval_status",
        "admin_remarks",
      ],
    },
    projectECRC: {
      columns: [
        "client_admission_no",
        "admission_date",
        "client_name",
        "age",
        "gender",
        "health_condition",
        "type_of_disorder",
        "type_of_diagnosis",
        "rescue_location",
        "client_native",
        "client_parent_details",
        "id_proofs",
        "client_pic",
        "treatment_taken",
        "medicine_taken",
        "skill_development_provided",
        "attachments",
        "rehabilitation_status",
        "date_of_abscond",
        "approval_status",
        "admin_remarks",
      ],
    },
    gallery: { columns: ["photo_urls"] },
    projectAwarenessProgram: {
      columns: [
        "program_date",
        "program_id",
        "event_name",
        "event_description",
        "program_location",
        "participant_count",
        "approval_status",
        "admin_remarks",
      ],
    },
    project5A: {
      columns: [
        "program_date",
        "program_id",
        "event_name",
        "event_description",
        "program_location",
        "participant_count",
        "approval_status",
        "admin_remarks",
      ],
    },
    projectHumanitarianServices: {
      columns: [
        "program_date",
        "program_id",
        "event_name",
        "event_description",
        "program_location",
        "participant_count",
        "approval_status",
        "admin_remarks",
      ],
    },
    projectAdmittedToOtherHomes: {
      columns: [
        "ot_regno",
        "outreach_date",
        "client_name",
        "age",
        "gender",
        "health_condition",
        "rescue_address",
        "client_pic",
        "home_name",
        "home_address",
        "admit_date",
        "staff_accommodation",
        "volunteer_accommodation",
        "first_month_follow_up",
        "second_month_follow_up",
        "third_month_follow_up",
        "fourth_month_follow_up",
        "approval_status",
        "admin_remarks",
      ],
    },
    outPatientServices: {
      columns: [
        "informer_id",
        "informer_date",
        "op_person_name",
        "age",
        "gender",
        "health_condition",
        "consent_relative",
        "informer_contact_detail",
        "informer_location",
        "informer_relationship",
        "client_pic",
        "attachments",
        "action_taken",
        "approval_status",
        "admin_remarks",
      ],
    },
    profilesClients: {
      columns: [
        "client_id",
        "client_name",
        "client_pic",
        "age",
        "health_condition",
        "gender",
        "rescue_address",
        "current_status",
        "approval_status",
        "admin_remarks",
      ],
    },
    profilesVolunteers: {
      columns: [
        "volunteer_name",
        "volunteer_pic",
        "age",
        "gender",
        "email",
        "father_name",
        "education_qualification",
        "blood_group",
        "location_address",
        "fb_acc",
        "insta_acc",
        "linkedin_acc",
        "approval_status",
        "admin_remarks",
      ],
    },
    profilesInformers: {
      columns: [
        "informer_id",
        "date_of_info",
        "informer_name",
        "contact_details",
        "informer_designation",
        "informer_native",
        "approval_status",
        "admin_remarks",
      ],
    },
    profilesOtherHomes: {
      columns: [
        "home_name",
        "home_location",
        "home_specialist",
        "founder_name",
        "gallery_id",
        "home_contact_no",
        "approval_status",
        "admin_remarks",
      ],
    },
    profilesStaffs: {
      columns: [
        "volunteer_name",
        "volunteer_pic",
        "age",
        "gender",
        "email",
        "father_name",
        "education_qualification",
        "blood_group",
        "location_address",
        "fb_acc",
        "insta_acc",
        "linkedin_acc",
        "approval_status",
        "admin_remarks",
      ],
    },
    programTimelines: {
      columns: [
        "program_date",
        "program_id",
        "event_name",
        "event_description",
        "program_location",
        "participant_count",
        "approval_status",
        "admin_remarks",
      ],
    },
    enquiries: {
      columns: [
        "gc_register_number",
        "enquire_date",
        "caller_name",
        "caller_location",
        "caller_phone_no",
        "homeless_person_name",
        "age",
        "gender",
        "health_condition",
        "homeless_person_location",
        "pic",
        "service_providing_details",
        "volunteer_accommodation",
        "approval_status",
        "admin_remarks",
      ],
    },
    alerts: { columns: ["alert_pic", "alert_name", "alert_description"] },
  },
};

module.exports = constants;
